In [1]:
import random as rn

class DateFinder:
    def __init__(self) -> None:
        self.days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Firday", "Saturday"]

        self.norm_doomse_days = ["04/04", "06/06", "08/08", "10/10", "12/12", "09/05", "05/09", "11/07", "07/11", "14/03"]
        self.rel_months = [date[3:5] for date in self.norm_doomse_days]

        self.changing_doomse_days = {
            "not_leap": ["03/01", "28/02"],
            "leap": ["04/01", "29/02"]
        }

        self.dooms_day_2000 = 2
    
    def is_leap(self, year: int):
        return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)
    
    def years_and_leap_years_since_2000(self, year: int):
        years_bw = abs(year - 2000)

        leaps_bw = int(years_bw / 4) - int(years_bw / 100) + int(years_bw / 400)
        
        if year < 2000:
            years_bw = -years_bw
            leaps_bw = -leaps_bw
            leaps_bw -= 1
        
        return years_bw, leaps_bw

    def calculate_doomsday_date(self, year: str):
        years_since_2000, leaps_since_2000 = self.years_and_leap_years_since_2000(int(year))

        return (self.dooms_day_2000 + years_since_2000 + leaps_since_2000) % 7
    
    def calculate_weekday(self, date: str):

        year = date[6:]
        
        dooms_day_date = self.calculate_doomsday_date(year)

        leap = self.is_leap(int(year))
        day_month = date[0:5]

        # if we were lucky enough to get and actual doomsday
        if day_month in self.norm_doomse_days or (not leap and day_month in self.changing_doomse_days["not_leap"]) or (leap and day_month in self.changing_doomse_days["leap"]):
            return self.days[dooms_day_date]
        
        day = date[0:2]
        month = date[3:5]

        int_month = int(month)

        # handles for feb and jan
        if int_month == 2:
            if leap:
                doomse_day = int(self.changing_doomse_days["leap"][1][0:2])
                diff = int(day) - doomse_day

                return self.days[(dooms_day_date + diff) % 7]
            else:
                doomse_day = int(self.changing_doomse_days["not_leap"][1][0:2])
                diff = int(day) - doomse_day

                return self.days[(dooms_day_date + diff) % 7]
        elif int_month == 1:
            if leap:
                doomse_day = int(self.changing_doomse_days["leap"][0][0:2])
                diff = int(day) - doomse_day

                return self.days[(dooms_day_date + diff) % 7]
            else:
                doomse_day = int(self.changing_doomse_days["not_leap"][0][0:2])
                diff = int(day) - doomse_day

                return self.days[(dooms_day_date + diff) % 7]
        else:
            month_index = self.rel_months.index(month)
            doomse_day = int(self.norm_doomse_days[month_index][0:2])
            diff = int(day) - doomse_day

            return self.days[(dooms_day_date + diff) % 7]

    def calculate_weekday_val(self, date:str):
        
        year = date[6:]
        
        dooms_day_date = self.calculate_doomsday_date(year)

        leap = self.is_leap(int(year))
        day_month = date[0:5]

        # if we were lucky enough to get and actual doomsday
        if day_month in self.norm_doomse_days or (not leap and day_month in self.changing_doomse_days["not_leap"]) or (leap and day_month in self.changing_doomse_days["leap"]):
            return dooms_day_date
        
        day = date[0:2]
        month = date[3:5]

        int_month = int(month)

        # handles for feb and jan
        if int_month == 2:
            if leap:
                doomse_day = int(self.changing_doomse_days["leap"][1][0:2])
                diff = int(day) - doomse_day

                return (dooms_day_date + diff) % 7
            else:
                doomse_day = int(self.changing_doomse_days["not_leap"][1][0:2])
                diff = int(day) - doomse_day

                return (dooms_day_date + diff) % 7
        elif int_month == 1:
            if leap:
                doomse_day = int(self.changing_doomse_days["leap"][0][0:2])
                diff = int(day) - doomse_day

                return (dooms_day_date + diff) % 7
            else:
                doomse_day = int(self.changing_doomse_days["not_leap"][0][0:2])
                diff = int(day) - doomse_day

                return (dooms_day_date + diff) % 7
        else:
            month_index = self.rel_months.index(month)
            doomse_day = int(self.norm_doomse_days[month_index][0:2])
            diff = int(day) - doomse_day

            return (dooms_day_date + diff) % 7
    
    def generate_random_date(self):
        month = rn.randint(1, 12)
        year = rn.randint(1, 6000)
        if month == 2 and self.is_leap(year):
            day_range = 29
        elif month == 2:
            day_range = 28
        elif month == 4 or month == 6 or month == 9 or month == 11:
            day_range = 30
        else:
            day_range = 31
        day = rn.randint(1, day_range)

        year_str = str(year)
        if month < 10:
            month_str = f"0{month}"
        else:
            month_str = str(month)
        if day < 10:
            day_str = f"0{day}"
        else:
            day_str = str(day)
        
        return f"{day_str}/{month_str}/{year_str}"
    
    def generate_random_day(self):
        date = self.generate_random_date()
        day_val = self.calculate_weekday_val(date)
        return {"date": date, "day_val": day_val, "day": self.days[day_val]}

finder = DateFinder()

finder.generate_random_day()

{'date': '16/02/4730', 'day_val': 0, 'day': 'Sunday'}

In [2]:
# lets generate the data
def generate_data(amount):
    full_data = []

    day_counter = {"Sunday": 0, "Monday": 0, "Tuesday": 0, "Wednesday": 0, "Thursday": 0, "Firday": 0, "Saturday": 0}

    while min(day_counter.values()) < amount:
        data = finder.generate_random_day()

        if day_counter[data["day"]] < amount:
            date = data["date"]
            day = int(date[0:2])
            month = int(date[3:5])
            year = int(date[6:])

            full_data.append([[day, month, year], data["day_val"]])

            day_counter[data["day"]] += 1
    
    return full_data, day_counter

data = generate_data(50_000)

In [3]:
# take a look at it
data[1]

{'Sunday': 50000,
 'Monday': 50000,
 'Tuesday': 50000,
 'Wednesday': 50000,
 'Thursday': 50000,
 'Firday': 50000,
 'Saturday': 50000}

In [4]:
# certain imports
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.activations import relu, softmax, sigmoid
from tensorflow.keras.losses import categorical_crossentropy
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import normalize

In [5]:
# seperate x and y, turn y into one hot vectors and make them np arrays

not_normilized = np.array([d[0] for d in data[0]])
not_one_hot = np.array([d[1] for d in data[0]])

# make y one hot encoded
shape_for_encoded = (not_one_hot.size, not_one_hot.max() + 1)

y = np.zeros(shape_for_encoded)

rows = np.arange(not_one_hot.size)

y[rows, not_one_hot] = 1



In [8]:
y[2], not_one_hot[2], not_normilized.shape[1], y.shape[1]

(array([0., 0., 0., 0., 1., 0., 0.]), 4, 3, 7)

In [9]:
# normalize X
days = not_normilized[:, 0] / 31
months = not_normilized[:, 1] / 12
years = not_normilized[:, 2]
years = years / years.max()
X = np.array(list(zip(days, months, years)), np.float)
X

array([[0.67741935, 0.08333333, 0.13616667],
       [0.22580645, 1.        , 0.53283333],
       [0.87096774, 0.25      , 0.16566667],
       ...,
       [0.93548387, 0.08333333, 0.126     ],
       [0.87096774, 0.08333333, 0.927     ],
       [0.96774194, 0.66666667, 0.482     ]])

In [10]:
# make model
model = Sequential(
    [
        Input(X.shape[1]),
        Dense(32, relu),
        Dense(32, relu),
        Dense(y.shape[1], sigmoid),
    ]
)

model.compile(Adam(), categorical_crossentropy, ["accuracy"])


In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                128       
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_2 (Dense)              (None, 7)                 231       
Total params: 1,415
Trainable params: 1,415
Non-trainable params: 0
_________________________________________________________________


In [13]:
output = model.fit(X, y, 32, 1, validation_split=0.01)

10829/10829 [==============================] - 11s 1ms/step - loss: 1.9460 - accuracy: 0.1416 - val_loss: 1.9469 - val_accuracy: 0.1249


In [158]:
#  make eval data
eval_data = generate_data(1000)

eval_x, noh = np.array([d[0] for d in data[0]]), np.array([d[1] for d in data[0]])

shape = (noh.size, noh.max() + 1)

eval_y = np.zeros(shape)

rows = np.arange(noh.size)

eval_y[rows, noh] = 1


In [206]:
np.argmax(model.predict(X[0: 10]), 1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [199]:
np.argmax(y[0:10], 1)

array([0, 0, 6, 2, 5, 0, 1, 6, 4, 4], dtype=int64)